version: "3"
services:
  web:
    image: pravinm/pythonapp:1.0
    deploy:
      replicas: 4
      restart_policy:
        condition: on-failure
    ports:
      - 4000:80
    networks:
      - webnet
networks:
  webnet:
  

